SHOW DATABASES; # SHOW THE CURRENT DATABASE
SHOW TABLES; # SHOW ALL THE TABLES FROM THE SELECTED DATABASE

SELECT * FROM CUSTOMERS;
SELECT * FROM EMPLOYEES;
SELECT * FROM OFFICES;
SELECT * FROM ORDERDETAILS;
SELECT * FROM ORDERS;
SELECT * FROM PAYMENTS;
SELECT * FROM PRODUCTLINES;
SELECT * FROM PRODUCTS;

/*




*/


# WRITE 10 TO 15 SELECT QUERY FROM THE ABOVE TABLES. CHECK ALL THE FIELDS PROPERLY.


#--------------------------------------------------------------------------------------------------
SELECT CUSTOMERNAME,CREDITLIMIT FROM CUSTOMERS WHERE CREDITLIMIT > 100000;

SELECT * FROM PRODUCTS WHERE PRODUCTLINE="Motorcycles";

SELECT * FROM PRODUCTS WHERE PRODUCTLINE="Motorcycles" AND QUANTITYINSTOCK > 6000 ORDER BY QUANTITYINSTOCK DESC;

SELECT * FROM PRODUCTS WHERE PRODUCTLINE="Motorcycles" OR QUANTITYINSTOCK > 8000 ORDER BY QUANTITYINSTOCK DESC;

SELECT * FROM OFFICES WHERE COUNTRY = "usa" ;

SELECT CONCAT(contactFirstName," ",contactLastName) as FullName,customerName FROM CUSTOMERS WHERE COUNTRY IN("USA","France");

SELECT * FROM CUSTOMERS WHERE STATE IS NOT NULL;

SELECT * FROM CUSTOMERS WHERE STATE IS NULL;

SELECT * FROM CUSTOMERS WHERE SALESREPEMPLOYEENUMBER BETWEEN 1000 AND 1500;

SELECT * FROM ORDERDETAILS WHERE QUANTITYORDERED NOT BETWEEN 30 AND 50;

SELECT * FROM PRODUCTS WHERE QUANTITYINSTOCK BETWEEN 400 AND 4000 AND MSRP >=30;

SELECT * FROM ORDERS WHERE STATUS = "Shipped";

SELECT * FROM EMPLOYEES WHERE JOBTITLE = "Sales Rep";

SELECT * FROM PRODUCTS WHERE PRODUCTVENDOR = "Highway 66 Mini Classics";

SELECT * FROM CUSTOMERS WHERE POSTALCODE="44000" OR COUNTRY = "France";

SELECT * FROM PAYMENTS WHERE AMOUNT >= 50000;

SELECT * FROM PAYMENTS WHERE PAYMENTDATE >= '2004-11-23';
